name       : spirv-headers
version    : 1.5.4
release    : 17
source     :
    - git|https://github.com/KhronosGroup/SPIRV-Headers.git : dafead1765f6c1a5f9f8a76387dcb2abe4e54acd
license    : MIT
component  : programming
summary    : Header files from the SPIR-V registry
description: |
    Machine-readable files for the SPIR-V Registry. This includes:
    
    - Header files for various languages.
    - JSON files describing the grammar for the SPIR-V core instruction set and the extended instruction sets.
    - The XML registry file.
    - A tool to build the headers from the JSON grammar.
patterns   :
    - /usr/include
setup      : |
    %cmake_ninja -DCMAKE_INSTALL_PREFIX=$installdir/usr
build      : |
    %ninja_build install-headers
install    : |
    # Default to unified spec
    ln -s /usr/include/spirv/unified1 $installdir/usr/include/SPIRV
