name       : spirv-headers
version    : 1.3
release    : 5
source     :
    - git|https://github.com/KhronosGroup/SPIRV-Headers.git : 02ffc719aa9f9c1dce5ce05743fb1afe6cbf17ea
license    : MIT
component  : programming
summary    : Header files from the SPIR-V registry
description: |
    Machine-readable files for the SPIR-V Registry. This includes:

    - Header files for various languages.
    - JSON files describing the grammar for the SPIR-V core instruction set and the extended instruction sets.
    - The XML registry file.
    - A tool to build the headers from the JSON grammar.
patterns   :
    - /usr/include
setup      : |
    mkdir solusBuildDir && cd solusBuildDir

    %cmake -DCMAKE_INSTALL_PREFIX=$installdir/usr \
           -GNinja ..
build      : |
    %meson_build install-headers
install    : |
    # Default to unified (1.3) spec
    ln -s /usr/include/spirv/unified1 $installdir/usr/include/SPIRV

