name       : spirv-headers
version    : 1.2
release    : 4
source     :
    - git|https://github.com/KhronosGroup/SPIRV-Headers.git : e0282aa7d54631502b4af567a85d3b6565fd5464
license    : MIT
component  : programming
summary    : The SPIR-V Tools project provides an API and commands for processing SPIR-V modules.
patterns   :
    - /usr/include
description: |
    The SPIR-V Tools project provides an API and commands for processing SPIR-V modules.
setup      : |
    mkdir build
    cd build
    %cmake ../ -DCMAKE_INSTALL_PREFIX=$installdir/usr
    cmake --build . --target install-headers
    # Default to 1.2 spec
    ln -s /usr/include/spirv/1.2 $installdir/usr/include/SPIRV
