name       : spirv-headers
version    : 1.3
release    : 9
source     :
    - git|https://github.com/KhronosGroup/SPIRV-Headers.git : e74c389f81915d0a48d6df1af83c3862c5ad85ab
license    : MIT
component  : programming
summary    : Header files from the SPIR-V registry
description: |
    Machine-readable files for the SPIR-V Registry. This includes:
    
    - Header files for various languages.
    - JSON files describing the grammar for the SPIR-V core instruction set and the extended instruction sets.
    - The XML registry file.
    - A tool to build the headers from the JSON grammar.
patterns   :
    - /usr/include
setup      : |
    %cmake_ninja -DCMAKE_INSTALL_PREFIX=$installdir/usr
build      : |
    %ninja_build install-headers
install    : |
    # Default to unified (1.3) spec
    ln -s /usr/include/spirv/unified1 $installdir/usr/include/SPIRV
