name       : spirv-headers
version    : 1.6.1
release    : 26
source     :
    - git|https://github.com/KhronosGroup/SPIRV-Headers.git : sdk-1.3.243.0
license    : MIT
component  : programming
summary    : Header files from the SPIR-V registry
description: |
    Machine-readable files for the SPIR-V Registry. This includes:

    - Header files for various languages.
    - JSON files describing the grammar for the SPIR-V core instruction set and the extended instruction sets.
    - The XML registry file.
    - A tool to build the headers from the JSON grammar.
patterns   :
    - /*
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Default to unified spec
    ln -s /usr/include/spirv/unified1 $installdir/usr/include/SPIRV
