name       : spirv-headers
version    : 1.1
release    : 2
source     :
    - git|https://github.com/KhronosGroup/SPIRV-Headers.git : 90dbe74b1f182aed7c4bd1cdccf1426df1032c49
license    : MIT
component  : programming
summary    : The SPIR-V Tools project provides an API and commands for processing SPIR-V modules.
patterns   :
    - /usr/include
description: |
    The SPIR-V Tools project provides an API and commands for processing SPIR-V modules.
setup      : |
    mkdir build
    cd build
    %cmake ../ -DCMAKE_INSTALL_PREFIX=$installdir/usr
    cmake --build . --target install-headers
    # Default to 1.1 spec
    ln -s /usr/include/spirv/1.1 $installdir/usr/include/SPIRV

